packages:
  - core/*
  - aztec/*
overrides:
  # Security overrides for lodash
  lodash@<4.17.21: '>=4.17.21'

  # Security overrides for various packages
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  braces@<3.0.3: '>=3.0.3'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  esbuild@<=0.24.2: '>=0.25.0'
  happy-dom@<15.10.2: '>=15.10.2'
  koa@<2.16.1: '>=2.16.1'
  micromatch@<4.0.8: '>=4.0.8'
  tough-cookie@<4.1.3: '>=4.1.3'

  # Security overrides for vite
  vite@>=6.0.0 <6.0.15: '>=6.0.15'
  vite@>=6.1.0 <6.1.5: '>=6.1.6'
