packages:
  - core/*
  - aztec/*

catalog:
  '@aztec/accounts': v3.0.0-nightly.20251203
  '@aztec/aztec.js': v3.0.0-nightly.20251203
  '@aztec/bb-prover': v3.0.0-nightly.20251203
  '@aztec/bb.js': v3.0.0-nightly.20251203
  '@aztec/blob-lib': v3.0.0-nightly.20251203
  '@aztec/builder': v3.0.0-nightly.20251203
  '@aztec/constants': v3.0.0-nightly.20251203
  '@aztec/entrypoints': v3.0.0-nightly.20251203
  '@aztec/ethereum': v3.0.0-nightly.20251203
  '@aztec/foundation': v3.0.0-nightly.20251203
  '@aztec/key-store': v3.0.0-nightly.20251203
  '@aztec/kv-store': v3.0.0-nightly.20251203
  '@aztec/l1-artifacts': v3.0.0-nightly.20251203
  '@aztec/merkle-tree': v3.0.0-nightly.20251203
  '@aztec/native': v3.0.0-nightly.20251203
  '@aztec/noir-acvm_js': v3.0.0-nightly.20251203
  '@aztec/noir-contracts.js': v3.0.0-nightly.20251203
  '@aztec/noir-noir_codegen': v3.0.0-nightly.20251203
  '@aztec/noir-noirc_abi': v3.0.0-nightly.20251203
  '@aztec/noir-protocol-circuits-types': v3.0.0-nightly.20251203
  '@aztec/noir-test-contracts.js': v3.0.0-nightly.20251203
  '@aztec/noir-types': v3.0.0-nightly.20251203
  '@aztec/protocol-contracts': v3.0.0-nightly.20251203
  '@aztec/pxe': v3.0.0-nightly.20251203
  '@aztec/simulator': v3.0.0-nightly.20251203
  '@aztec/stdlib': v3.0.0-nightly.20251203
  '@aztec/telemetry-client': v3.0.0-nightly.20251203
  '@aztec/test-wallet': v3.0.0-nightly.20251203
  '@aztec/world-state': v3.0.0-nightly.20251203
  '@biomejs/biome': 2.2.4
  '@changesets/cli': ^2.29.7
  '@vitest/coverage-v8': 3.2.4
  typedoc: ^0.28.14
  typedoc-plugin-markdown: ^4.9.0
  typescript: 5.9.3
  vitest: 3.2.4

catalogMode: strict

ignoredBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - classic-level
  - esbuild
  - lmdb
  - msgpackr-extract
  - protobufjs
  - utf-8-validate

linkWorkspacePackages: true

onlyBuiltDependencies:
  - c-kzg

overrides:
  lodash@<4.17.21: '>=4.17.21'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  braces@<3.0.3: '>=3.0.3'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  esbuild@<=0.24.2: '>=0.25.0'
  happy-dom@<15.10.2: '>=15.10.2'
  koa@<2.16.1: '>=2.16.1'
  micromatch@<4.0.8: '>=4.0.8'
  tough-cookie@<4.1.3: '>=4.1.3'
  request@<2.88.2: '>=2.88.2'
  vite@>=6.0.0 <6.0.15: '>=6.0.15'
  vite@>=6.1.0 <6.1.5: '>=6.1.6'
  abstract-leveldown: npm:classic-level@1.3.0
  deferred-leveldown: npm:classic-level@1.3.0
  level-concat-iterator: npm:classic-level@1.3.0
  level-errors: npm:classic-level@1.3.0
  leveldown: npm:classic-level@1.3.0
  levelup: npm:classic-level@1.3.0
  memdown: npm:memory-level@1.0.0
  lodash.isequal: npm:lodash@4.17.21
  lodash.chunk: npm:lodash@4.17.21
  lodash.omit: npm:lodash@4.17.21

preferWorkspacePackages: true
