import { WalletContextValue } from '@walletmesh/modal';
import { EnhancedConnection } from '@walletmesh/modal';

// ...existing code...
const { activeWallets } = useWalletContext();

// ...existing code...
return activeWallets.find((c: EnhancedConnection) =>
// ...existing code...

return activeWallets.find((c: EnhancedConnection) => c.chain.id === chainId || c.chain.chainId === chainId);
// ...existing code...

return activeWallets.find((c: EnhancedConnection) => c.wallet.id === walletId);
// ...existing code...